[package]
name = "working-tlds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hickory-resolver = "0.24.0"
itertools = "0.12.0"
rayon = "1.8.0"
tap = "1.0.1"
ureq = "2.9.1"
